language: java

mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

mvn test -B

default_text_charset: 'utf-8'

notifications:
  email:
    - umberto.picarielloa@gmail.com
    - c.capo4@studenti.unisa.it
    - alessioromanouni@gmail.com
