language: java

jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  
script: ant build

addons:
    apt:
    packages:
    - oracle-java8-installer

default_text_charset: 'utf-8'

notifications:
  email:
    - umberto.picarielloa@gmail.com
    - c.capo4@studenti.unisa.it
    - alessioromanouni@gmail.com
