language: java

jdk:
  - oraclejdk8
  
env:
  - TESTFOLDER=batch
  - TESTFOLDER=cdi
  - TESTFOLDER=concurrency
  - TESTFOLDER=ejb
  - TESTFOLDER=el
  - TESTFOLDER=interceptor
  - TESTFOLDER=jacc
  - TESTFOLDER=jaspic
  - TESTFOLDER=javamail
  - TESTFOLDER=jaxrs
  - TESTFOLDER=jaxws
  - TESTFOLDER=jca
  - TESTFOLDER=jms
  - TESTFOLDER=jpa
  - TESTFOLDER=jsf
  - TESTFOLDER=json
  - TESTFOLDER=jta
  - TESTFOLDER=servlet
  - TESTFOLDER=validation
  - TESTFOLDER=websocket 

script: ant build

default_text_charset: 'utf-8'

notifications:
  email:
    - umberto.picarielloa@gmail.com
    - c.capo4@studenti.unisa.it
    - alessioromanouni@gmail.com
