language: java

install: ant dependencies

jdk:
  - oraclejdk8
  
script: ant build

default_text_charset: 'utf-8'

notifications:
  email:
    - umberto.picarielloa@gmail.com
    - c.capo4@studenti.unisa.it
    - alessioromanouni@gmail.com
