language: java
jdk:
  - oraclejdk8
  - oraclejdk9
  - openjdk8
  
script: ant build

notifications:
  email:
    - umberto.picarielloa@gmail.com
    - c.capo4@studenti.unisa.it
    - alessioromanouni@gmail.com
