language: java
jdk:
  - oraclejdk8
  
script: ant build

before_install:
  - cd java
 
notifications:
  email:
    - umberto.picarielloa@gmail.com
    - c.capo4@studenti.unisa.it
    - alessioromanouni@gmail.com
