use ChooseIT;

load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/utente.txt' into table utente fields terminated by ',' lines terminated by '\n' (email, pwd, nome, cognome, telefono, indirizzo, data_nascita, foto_profilo);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/studente.txt' into table studente fields terminated by '-' lines terminated by '\n' (email, matricola, descrizione);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/segreteria.txt' into table segreteria lines terminated by ',' (email);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/presidente.txt' into table presidente lines terminated by ',' (email);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/tutor_universitario.txt' into table tutor_universitario lines terminated by ',' (email);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/azienda.txt' into table azienda fields terminated by '-' lines terminated by '\n' (ragione_sociale, progetto_formativo, sede_operativa, sede_legale);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/tutor_aziendale.txt' into table tutor_aziendale fields terminated by ',' lines terminated by '-' (email, azienda_id);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/registro_tirocinio.txt' into table registro_tirocinio fields terminated by ',' lines terminated by '+' (studente_email, data_inizio, tutor_aziendale_email, tutor_universitario_email);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/stato_tirocinio.txt' into table stato_tirocinio fields terminated by ',' lines terminated by '\n' (data_stato, tipo, registro_id);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/questionario_valutativo_studente.txt' into table questionario_valutativo_studente fields terminated by ',' lines terminated by '-' (registro_id, pdt_1, pdt_2, pdt_3, pdt_4, t_1, t_2, t_3,
t_4, su_1, su_2, su_3);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/questionario_valutativo_ente_ospitante.txt' into table questionario_valutativo_ente_ospitante fields terminated by ',' lines terminated by '-' (registro_id, pdt_1, pdt_2, pdt_3, pdt_4, pdt_5, eo_1, eo_2, eo_3,
eo_4, eo_5, su_1, su_2, su_3);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/report.txt' into table report fields terminated by ',' lines terminated by '+' (registro_id, data_inserimento, contenuto, tutor_aziendale_email);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/stato_report.txt' into table stato_report fields terminated by ',' lines terminated by '+' (data_stato, tipo, report_id_reg, report_data);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/feedback.txt' into table feedback fields terminated by ',' lines terminated by '\n' (email_studente, ragione_sociale_azienda, descrizione);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/richiesta_tirocinio.txt' into table richiesta_tirocinio fields terminated by ',' lines terminated by '+' (studente_email, registro_id, ragione_sociale_azienda, progetto_formativo, data_richiesta);
load data local infile 'D:/Uni/Terzo Anno/Primo Semestre/Ingegneria Del Software/Progetto/databaseChooseIT/popolamento/stato_richiesta.txt' into table stato_richiesta fields terminated by ',' lines terminated by '\n' (data_stato, tipo, richiesta_id);